export struct UiParameter {
    id: int,
    normalized-value: float,
    default-normalized-value: float,
    display-value: string,
}

export component PluginWindow inherits Window {
    width: 400px;
    height: 300px;

    in property <UiParameter> gain;

    callback start-parameter-change(int);
    callback change-parameter-value(int, float);
    callback change-parameter-string(int, string);
    callback end-parameter-change(int);    

    Text {
        text: gain.display-value;
        font-size: 40px;

        TouchArea {
            double-clicked => {
                start-parameter-change(gain.id);
                change-parameter-value(gain.id, gain.default-normalized-value);
                end-parameter-change(gain.id);
            }        
        }
    }
}
