pub enum Feature {
    Analyzer,
    AudioEffect,
    Instrument,
    NoteDetector,
    NoteEffect,

    Chorus,    
    Compressor,
    DeEsser,
    Delay,
    Distortion,
    Drum,
    DrumMachine,
    Equalizer,
    Expander,
    Filter,
    Flanger,
    FrequencyShifter,
    Gate,
    Glitch,
    Granular,
    Limiter,
    Mastering,
    Mixing,
    MultiEffects,
    Phaser,
    PhaseVocoder,
    PitchCorrection,
    PitchShifter,
    Restoration,
    Reverb,    
    Sampler,
    Synthesizer,
    TransientShaper,
    Tremolo,
    Utility,

    Ambisonic,
    Mono,
    Stereo,
    Surround,
}

impl Feature {
    pub fn to_str(&self) -> &str {
        match self {
            Feature::Analyzer => "analyzer",
            Feature::AudioEffect => "audio-effect",
            Feature::Instrument => "instrument",
            Feature::NoteDetector => "note-detector",
            Feature::NoteEffect => "note-effect",

            Feature::Chorus => "chorus",
            Feature::Compressor => "compressor",
            Feature::DeEsser => "de-esser",
            Feature::Delay => "delay",
            Feature::Distortion => "distortion",
            Feature::Drum => "drum",
            Feature::DrumMachine => "drum-machine",
            Feature::Equalizer => "equalizer",
            Feature::Expander => "expander",
            Feature::Filter => "filter",
            Feature::Flanger => "flanger",
            Feature::FrequencyShifter => "frequency-shifter",
            Feature::Gate => "gate",
            Feature::Glitch => "glitch",
            Feature::Granular => "granular",
            Feature::Limiter => "limiter",
            Feature::Mastering => "mastering",
            Feature::Mixing => "mixing",
            Feature::MultiEffects => "multi-effects",
            Feature::Phaser => "phaser",
            Feature::PhaseVocoder => "phase-vocoder",
            Feature::PitchCorrection => "pitch-correction",
            Feature::PitchShifter => "pitch-shifter",
            Feature::Restoration => "restoration",
            Feature::Reverb => "reverb",
            Feature::Sampler => "sampler",
            Feature::Synthesizer => "synthesizer",
            Feature::TransientShaper => "transient-shaper",
            Feature::Tremolo => "tremolo",
            Feature::Utility => "utility",
           
            Feature::Ambisonic => "ambisonic",
            Feature::Mono => "mono",
            Feature::Stereo => "stereo",
            Feature::Surround => "surround",
        }
    }
}
