#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum Cursor {
    None,
    Alias,
    #[default]
    Arrow,
    Copy,
    Crosshair,
    Grab,
    Grabbing,
    Help,
    Move,
    NoDrop,
    NotAllowed,
    Pointer,
    Progress,
    Text,
    Wait,

    ResizeColumn,
    ResizeRow,
    ResizeNorth,
    ResizeNorthEast,
    ResizeEast,
    ResizeSouthEast,
    ResizeSouth,
    ResizeSouthWest,
    ResizeWest,
    ResizeNorthWest,
    ResizeEastWest,
    ResizeNorthSouth,
    ResizeNorthEastSouthWest,
    ResizeNorthWestSouthEast,
}
