name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  VST3_SDK_DIR: ${{ github.workspace }}/vst3sdk

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v5

    - name: Clone vst3sdk
      uses: actions/checkout@v5
      with:
        repository: steinbergmedia/vst3sdk
        path: vst3sdk

    - name: Init vst3sdk submodules
      run: |
        cd vst3sdk
        git submodule update --init base cmake pluginterfaces public.sdk

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
